### ISSUE TITLE
allow switching to micromamba

### ISSUE THREAD

**Issue by proppy** [conda-incubator/condacolab#24]
I'd be nice to allow to point `.install` method to https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html in order to speed up the installation process.

**Comment by jaimergp** [comment]
Thanks! Yes, this is planned in a future release. As a workaround, you can rely on `mambaforge` (default option) and use `!mamba` to install your packages.

**Comment by jaimergp** [comment]
We've thought about this and #31 implements a different strategy where we procure a new Python installation. Since we need `ipykernel` too, which requires Python anyway, using `micromamba` doesn't really offer much of an advantage over `mamba`. E.g. using `micromamba` to then install `python`, `ipykernel` and some other dependencies won't be faster than installing `mambaforge` to begin with.

Make sure to check the pre-release with `!pip install -q https://github.com/conda-incubator/condacolab/archive/main.tar.gz` and let us know how it goes!
