### ISSUE TITLE
Your pinning does not match what's currently installed

### ISSUE THREAD

**Issue by effepivi** [conda-incubator/condacolab#47]
Hi there.

I install the package as follows:

```python
!pip install -q condacolab
import condacolab
condacolab.install()
```

The runtime restarts. When I try to install packages, e.g. using 
```python
!mamba install -c conda-forge -c intel -c astra-toolbox -c ccpi cil numpy astra-toolbox --quiet
```

I get the error as follows:

```
Your pinning does not match what's currently installed. Please remove the pin and fix your installation
  Pin: python=3.9
  Currently installed: conda-forge/linux-64::python==3.8.15=h4a9ceb5_0_cpython
```

Note that I did not have the issue yesterday. Yesterday I believe Google Collaborative worked with Python 3.8. It somehow has changed.

Regards,

**Comment by WYVERN2742** [comment]
This is due to colab now using python 3.9; they've rolled out a new version yesterday evening
https://github.com/googlecolab/colabtools/issues/3450

Current workaround includes;
1. Connecting to a runtime without running conda-colab installation (click on reconnect kernal status) 
![image](https://user-images.githubusercontent.com/35181365/224048642-b23a5902-0edf-4a85-88fe-71a17b708f0a.png)
2. Opening the command palette 
![image](https://user-images.githubusercontent.com/35181365/224048821-6a58e3b1-b2a6-48e6-bb64-5bbf7ada942a.png)
3. Using fallback runtime
![image](https://user-images.githubusercontent.com/35181365/224048870-0b8ceef9-003f-4828-af85-243f5951fd58.png)

From the earlier colab issue, this will only work for the next few weeks

**Comment by jaimergp** [comment]
Hi, thanks for the report!

Can you try with this hotfix? If it works I'll cut a new 0.1.x release:

```python
!pip install -q https://github.com/conda-incubator/condacolab/archive/py39.tar.gz
import condacolab
condacolab.install()
```

**Comment by effepivi** [comment]
Hi @jaimergp

it works like a charm ([see](https://github.com/effepivi/gvxr-tutorials/blob/main/PoissonNoise.ipynb). Please let me know when you deploy the solution. And a big thank for this wonderful project. It's so useful!

**Comment by jaimergp** [comment]
0.1.6 is now out!

- https://github.com/conda-incubator/condacolab/releases/tag/v0.1.6
- https://pypi.org/project/condacolab/
